site_name: MLCommons Science
site_url: https://mlcommons-science.github.io
docs_dir: content

theme:
  name: material
  custom_dir: content/overrides
  logo: https://mlcommons.org/wp-content/themes/mlcommons/build/img/ML-Commons-Logo.svg
  palette:
    primary: custom
    accent: custom
  font:
    text: Inter
  features:
    - navigation.sections
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - About: about.md
  - Blog: blog.md
  - Meetings: meetings.md
